version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "127.0.0.1:4000:127.0.0.1:3001"

    environment:
      NODE_ENV: production
      PORT: 3001

    restart: unless-stopped

    networks:
      - spacycookinghere

networks:
  spacycookinghere: