version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "4000:3001"

    environment:
      NODE_ENV: production
      PORT: 3001

    restart: unless-stopped

    networks:
      - spacycookinghere

networks:
  spacycookinghere: