version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "4000:3001"
    networks:
      - spacycookinghere
    environment:
      NODE_ENV: production
      PORT: 3001


networks:
  spacycookinghere:
  